---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  CART_HOST: "cart:80"
  USER_HOST: "user"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    name: payment
    tier: app
spec:
  containers:
  - name: payment
    imagePullPolicy: Always
    image: techworldwithsiva/payment:k8
    envFrom:
    - configMapRef:
        name: payment-config
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    name: payment
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

